// Glossário do NOC: termo, apelidos (como aparecem nas aulas) e definição curta.
// Termos em <b> nas aulas e explicações que batem com um item daqui viram tocáveis.
export const GLOSS = [
  ['Access point', ['access point', 'ap'], 'Equipamento que leva a rede para o Wi-Fi, ligando os aparelhos sem fio à rede com cabo.'],
  ['ACL', ['acl', 'lista de acesso'], 'Lista de regras (permitir/negar) que o roteador ou firewall confere de cima para baixo para cada pacote.'],
  ['ARP', ['arp'], 'Protocolo que descobre o MAC de um IP na rede local: "quem tem 192.168.1.1?" e o dono responde.'],
  ['ARP spoofing', ['arp spoofing'], 'Ataque em que alguém responde ARP fingindo ser outro IP (geralmente o gateway) para o tráfego passar por ele.'],
  ['AS', ['as', 'asn'], 'Sistema Autônomo: uma rede com política de rotas própria (provedor, empresa grande), identificada por um número.'],
  ['Bit', ['bit', 'bits', '8 bits', '32 bits'], 'A menor unidade de informação: 0 ou 1. 8 bits formam um octeto.'],
  ['BGP', ['bgp'], 'Protocolo que os AS da internet usam para trocar rotas entre si. Roda em TCP 179.'],
  ['Broadcast', ['broadcast'], 'Mensagem para todos da rede local. Também é o último endereço de uma rede IP.'],
  ['C2', ['c2'], 'Comando e controle: o servidor do atacante que dá ordens ao malware instalado nas vítimas.'],
  ['Camadas', ['camadas', 'tcp/ip', 'osi'], 'Modelo que divide a rede em níveis (enlace, internet, transporte, aplicação), cada um com um trabalho.'],
  ['CGNAT', ['cgnat'], 'NAT feito pelo provedor para vários clientes dividirem um IP público. Usa a faixa 100.64.0.0/10 (RFC 6598).'],
  ['CIDR', ['cidr', '/24', '/16', '/8'], 'Forma curta de escrever a máscara: o número de bits de rede. /24 = 255.255.255.0.'],
  ['DDoS', ['ddos', 'ddos volumétrico', 'ddos de protocolo'], 'Ataque de negação de serviço vindo de muitas origens ao mesmo tempo, para derrubar um serviço ou encher o link.'],
  ['DHCP', ['dhcp'], 'Serviço que entrega IP, máscara, gateway e DNS automaticamente, em 4 passos (Discover, Offer, Request, Ack).'],
  ['DNS', ['dns', 'resolvedor dns'], 'Serviço que traduz nomes (google.com) em endereços IP. Usa a porta 53.'],
  ['DORA', ['dora'], 'Os 4 passos do DHCP: Discover, Offer, Request e Ack.'],
  ['Endereço IP', ['ip', 'endereço ip', 'ipv4'], 'Endereço da máquina na rede. No IPv4 são 4 números de 0 a 255, como 192.168.1.10.'],
  ['Endereço MAC', ['mac', 'endereço mac'], 'Identificação gravada na placa de rede, em 6 pares hexadecimais. Vale só na rede local.'],
  ['Fibra monomodo', ['fibra monomodo'], 'Fibra de núcleo fino (9 µm) em que a luz segue um caminho só. Vai a quilômetros.'],
  ['Fibra multimodo', ['fibra multimodo'], 'Fibra de núcleo mais largo (50 µm) para centenas de metros, dentro do prédio ou campus.'],
  ['Firewall', ['firewall'], 'Equipamento ou software que filtra o tráfego por regras: o que pode entrar e sair.'],
  ['Gateway', ['gateway', 'default'], 'A saída da rede local: o roteador para onde vai tudo que não é da própria rede.'],
  ['Handshake', ['handshake'], 'O aperto de mão do TCP antes de conversar: SYN, SYN-ACK, ACK.'],
  ['Host', ['host'], 'Qualquer equipamento com endereço na rede: PC, servidor, impressora, celular.'],
  ['ICMP', ['icmp'], 'Protocolo de mensagens de controle da rede. O ping usa ICMP.'],
  ['IoC', ['ioc'], 'Indicador de comprometimento: IP, domínio, arquivo ou comportamento que mostra uma invasão.'],
  ['Lease', ['lease'], 'O tempo que o IP do DHCP fica emprestado. Antes de vencer, o aparelho pede para renovar.'],
  ['Link-local', ['169.254.x.x', 'link-local'], 'Endereço 169.254.x.x que o aparelho se dá quando o DHCP não responde. Não sai da rede local.'],
  ['Máscara', ['máscara'], 'Diz quanto do IP é rede e quanto é host. Bits 1 = rede, bits 0 = host.'],
  ['NAT', ['nat'], 'Tradução de endereço: o roteador troca o IP privado pelo público na saída e desfaz na volta.'],
  ['NTP', ['ntp'], 'Protocolo que acerta o relógio dos equipamentos. Usa UDP 123.'],
  ['Octeto', ['octeto'], 'Grupo de 8 bits. O IPv4 tem 4 octetos, cada um de 0 a 255.'],
  ['Ping', ['ping'], 'Teste que manda um ICMP e espera a resposta: diz se o destino responde e em quanto tempo.'],
  ['PoE', ['poe'], 'Power over Ethernet: energia pelo próprio cabo de rede, para câmera, telefone IP e access point.'],
  ['Porta', ['porta', 'portas'], 'Número de 0 a 65535 que diz qual programa recebe a conversa no destino. Ex.: 443 = HTTPS.'],
  ['Porta de origem', ['porta de origem'], 'A porta de quem envia o pacote. Na reflexão, a resposta chega com a porta do serviço abusado como origem.'],
  ['IP privado', ['privadas', 'rfc 1918'], 'Faixas que não andam na internet: 10.0.0.0/8, 172.16.0.0/12 e 192.168.0.0/16.'],
  ['Protocolo', ['protocolo'], 'Conjunto de regras de conversa entre equipamentos, como TCP, UDP, HTTP ou DNS.'],
  ['Rede', ['rede'], 'Grupo de equipamentos que conversam entre si. No IP, também é o primeiro endereço do bloco.'],
  ['Redirecionamento de porta', ['redirecionamento de porta'], 'Regra de NAT que manda o que chega numa porta do IP público para um servidor interno.'],
  ['Reflexão', ['reflexão', 'amplificação', 'reflexão ntp'], 'Ataque em que o atacante forja o IP da vítima e servidores abertos mandam respostas grandes para ela.'],
  ['Roteador', ['roteador'], 'Equipamento que liga redes diferentes e escolhe o caminho pelo IP de destino.'],
  ['RPKI', ['rpki', 'roa', 'rov'], 'Sistema que registra qual AS pode anunciar cada bloco de IP (o ROA), para descartar anúncios falsos.'],
  ['Servidor', ['servidor'], 'Computador que oferece um serviço para os outros: site, arquivos, e-mail, DNS.'],
  ['Spoofing', ['spoofing', 'anti-spoofing'], 'Falsificar o endereço de origem de um pacote. O BCP 38 manda filtrar isso na borda.'],
  ['STP', ['stp', 'rstp'], 'Spanning Tree: bloqueia caminhos duplicados entre switches para não formar loop e libera se o principal cair.'],
  ['Sub-rede', ['sub-rede', 'sub-redes'], 'Pedaço de uma rede maior, criado pegando bits de host emprestados para a parte de rede.'],
  ['Switch', ['switch'], 'Equipamento que liga os aparelhos da mesma rede local e entrega cada quadro pelo MAC.'],
  ['SYN flood', ['syn flood'], 'Ataque que manda muitos SYN e nunca completa o handshake, até lotar a fila do servidor.'],
  ['TCP', ['tcp'], 'Transporte com confirmação: abre conexão, numera, confirma e reenvia o que se perdeu.'],
  ['Terminal', ['terminal', 'terminal linux'], 'Tela de texto em que você digita comandos e o equipamento responde.'],
  ['Traceroute', ['traceroute'], 'Teste que mostra cada roteador (salto) no caminho até o destino.'],
  ['Transceiver', ['transceiver', 'sr', 'lr'], 'Módulo (SFP) que converte o sinal elétrico em luz para a fibra. SR = curta distância, LR = longa.'],
  ['UDP', ['udp'], 'Transporte sem confirmação: manda e segue. Leve e rápido, bom para voz, DNS e DHCP.'],
  ['VLAN', ['vlan'], 'Rede local virtual: separa grupos de portas num mesmo switch como se fossem redes diferentes.'],
  ['Wildcard', ['wildcard'], 'O inverso da máscara, usado em ACLs Cisco: 255 menos cada octeto. /24 → 0.0.0.255.'],
  ['Wireshark', ['wireshark'], 'Programa que captura e mostra cada pacote da rede, com filtros para achar o que interessa.']
];
const norm = s => s.toLowerCase().replace(/\s+/g, ' ').trim();
const IDX = new Map(); GLOSS.forEach((g, i) => [g[0], ...g[1]].forEach(a => IDX.set(norm(a), i)));
export const findGloss = text => { const i = IDX.get(norm(text)); return i === undefined ? null : GLOSS[i]; };
